---
- name: Setup Nginx server
  hosts: all
  become: yes

  tasks:
  - name: Ensure System Updated
    apt:
      update_cache: yes

  - name: Ensure Nginx present
    file:
      name: nginx
      state: present